/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//void  idle(void);
void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);



uint32_t getPSP_Value_fromTask( void);
void  savePSP_Value_toTask(uint32_t pspValue );

typedef  struct {
	uint32_t  pPSPValue ;
	uint32_t block_count;
	uint8_t taskState;
	void (*taskHandler)( void);
}uHandle_Task;

uHandle_Task user_Tasks[MAX_TASKS] ;

void enable_processor_faults(void);
__attribute__((naked))  void init_scheduler_stack(uint32_t  top_scheduler_stck);
void init_tasks_stack(void);
void init_systick_timer(uint32_t TickCounter);
__attribute__((naked)) void switch_sp_to_psp(void);
void update_next_task (void);


uint8_t Current_task = 1;
uint32_t gSysTick_Counter = 0;

int main(void)
{
    /* Loop forever */
	enable_processor_faults();

	init_scheduler_stack(SCHED_STACK_START);

	init_tasks_stack();

	led_init_all();

	init_systick_timer(TICK_HZ);

	switch_sp_to_psp();

	task1_handler();

	for(;;);
}

void idle(void)
{
	while(1)
	{
		printf("IDLE \n ");
	}
}
void task1_handler(void)
{
	while(1)
	{
		printf("TASK 1\n ");

	}
}

void task2_handler(void)
{
	while(1)
	{
		printf("TASK 2 \n ");
	}
}

void task3_handler(void)
{
	while(1)
	{
		printf("TASK 3 \n");
		led_on(LED_RED);
	}
}

void task4_handler(void)
{
	while(1)
	{
		printf(" TASK 4 \n");
		led_on(LED_ORANGE);
	}
}


void enable_processor_faults (void)
{
	uint32_t * pSHCSR =  (uint32_t*) (0xE000ED24);
	*pSHCSR |= ( 1 << 16);  // Memory fault activation
	*pSHCSR |= ( 1 << 17); // Bus fault activation
	*pSHCSR |= ( 1 << 18); // Usage fault activation
}

__attribute__((naked))  void init_scheduler_stack(uint32_t  top_scheduler_stck)
{

	__asm volatile ("MSR MSP , %0" :  :"r" (top_scheduler_stck) : );  // as we are moving value to a special register and not the general register like R0 to R12
	__asm volatile ("BX LR");  // Return from function call
	// we use BL funC  -- for Branch with link  (Call)  to function  funC, return address stored in LR

 }

void init_tasks_stack(void)
{
	//create a local pointer  to  pointing to  the PSP of each task
	uint32_t *pSP;

	// then assigned the value of  each task's PSP value there respective addresses
	user_Tasks[0].pPSPValue =  IDLE_STACK_START ;
	user_Tasks[1].pPSPValue  = T1_STACK_START ;
	user_Tasks[2].pPSPValue  = T2_STACK_START ;
	user_Tasks[3].pPSPValue = T3_STACK_START;
	user_Tasks[4].pPSPValue  = T4_STACK_START;

	user_Tasks[0].taskHandler = idle;
	user_Tasks[1].taskHandler = task1_handler;
	user_Tasks[2].taskHandler = task2_handler;
	user_Tasks[3].taskHandler = task3_handler;
	user_Tasks[4].taskHandler = task4_handler;

	user_Tasks[0].taskState =  TASK_READY_STATE;
	user_Tasks[1].taskState =  TASK_READY_STATE;
	user_Tasks[2].taskState =  TASK_READY_STATE;
	user_Tasks[3].taskState =  TASK_READY_STATE;
	user_Tasks[4].taskState =  TASK_READY_STATE;



	// also assigned for each task the initial value of PSR , PC and LR , R12, R3 , R2, R1, R0 by decrementing the PSP pointer
	for ( int i = 0;  i < MAX_TASKS ; i++)
	{
		pSP =  (uint32_t*)(user_Tasks[i].pPSPValue) ;

		pSP--;
		// the first register is PSR
		*pSP =  DUMMY_XPSR;

		// the second is the PC  as the processor is suppose to return back to task handler after the interrupt
		pSP-- ;
		*pSP = (uint32_t) user_Tasks[i].taskHandler;

		// the third is the LR
		pSP-- ;
		*pSP = 0xFFFFFFFD ;

		for (int j = 0 ; j < 13 ; j++) // the rest of  13 register value is initialized to zero
		{
			pSP-- ;
			*pSP = 0 ;
		}

		user_Tasks[i].pPSPValue =  (uint32_t)pSP;
	}
}

void init_systick_timer(uint32_t TickCounter)
{
	uint32_t cntValue  = ( (SYSTICK_TIM_CLK / TickCounter) - 1);

	uint32_t* pSTK_CTRL  =  (uint32_t*) 0xE000E010;
	uint32_t* pSTK_LOAD =  (uint32_t*) 0xE000E014;

	//we need to load the value of counter into STK_LOAD register from bit[23:0]

	*pSTK_LOAD &= ~(0x00FFFFFFFF);

	*pSTK_LOAD |= cntValue;

	// now we need to enable the bit of STK_CTRL
	*pSTK_CTRL |=  ( 1 << 1);
	*pSTK_CTRL |=  ( 1 << 2);
	*pSTK_CTRL |=  ( 1 << 0);
}

__attribute__((naked)) void switch_sp_to_psp(void)
{
	// we need to push LR hear
	__asm volatile ("PUSH {LR}"); // we are using this because inside this function we are going to branch to other function to get the PSP value , so the original value of LR is going to modify

	// get the PSP value in the RO
	__asm volatile ("BL getPSP_Value_fromTask");

	// store to the  PSP  value  in SP register of core
	__asm volatile ("MSR PSP, R0");

	__asm volatile("POP {LR}");  //--- till here we were using  MSP in thread mode


	// change the SP type to PSP from MSP
	//change SP to PSP using CONTROL register
	__asm volatile ("MOV R0,#0X02");
	__asm volatile ("MSR CONTROL,R0");

	__asm volatile ("BX LR");

}


uint32_t getPSP_Value_fromTask(void){
	return user_Tasks[Current_task].pPSPValue;
}

void  savePSP_Value_toTask(uint32_t pspValue ){
	user_Tasks[Current_task].pPSPValue = pspValue;
}


void update_next_task (void)
{
	uint8_t state = TASK_BLOCKED_STATE;
//
	for(int i = 0 ; i < (MAX_TASKS) ; i++)
	{
		Current_task++;
		Current_task = Current_task  % (MAX_TASKS);
//		if ( Current_task >= MAX_TASKS) Current_task = 1;
		state = user_Tasks[Current_task].taskState;
		if( (state == TASK_READY_STATE) && (Current_task != 0) )
			break;
	}

//	if ( Current_task >= MAX_TASKS) Current_task = 1;
}

// implementing the Systick handler
__attribute__((naked)) void SysTick_Handler (void){
    //	gSysTick_Counter++ ;

    /*Save the context of current task */
	//1. Get current running task's PSP value
	__asm volatile("MRS R0,PSP");
	//2. Using that PSP value store SF2( R4 to R11)
	__asm volatile("STMDB R0!,{R4-R11}");

	__asm volatile("PUSH {LR}");

	//3. Save the current value of PSP
    __asm volatile("BL savePSP_Value_toTask");

	/*Retrieve the context of next task */
	//1. Decide next task to run
    __asm volatile("BL  update_next_task");

	//2. get its past PSP value
	__asm volatile ("BL getPSP_Value_fromTask");

	//3. Using that PSP value retrieve SF2(R4 to R11)
	__asm volatile ("LDMIA R0!,{R4-R11}");

	//4. update PSP and exit
	__asm volatile("MSR PSP,R0");

	__asm volatile("POP {LR}");

	__asm volatile("BX LR");

}


//2. implement the fault handlers
void HardFault_Handler(void)
{
	printf(" Hard fault occurred \n");
	while (1)
	{

	}
}

void MemManage_Handler(void)
{
	printf(" Mem manage fault occurred \n");
	while (1)
	{

	}
}

void BusFault_Handler(void)
{
	printf(" Bus hard  fault occurred \n");
	while (1)
	{

	}
}














