/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void enable_processor_faults(void);


int main(void)
{
    /* Loop forever */
	enable_processor_faults();

//	init_scheduler_stack(SCHED_STACK_START);

//	init_tasks_stack();

//	led_init_all();

//	init_systick_timer(TICK_HZ);

//	switch_sp_to_psp();

//	task1_handler();

	for(;;);
}


void enable_processor_faults ()
{
	uint32_t * pSHCSR =  (uint32_t*) (0xE000ED00  +  0x24);

	*pSHCSR |= ( 1U << 16);  // Memory fault activation
	*pSHCSR |= ( 1U << 17); // Bus fault activation
	*pSHCSR |= ( 1U << 18); // Usage fault activation

}



